# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류 발생
version: 0.0
os: linux
files:
# source -> 전달해준 파일 중 destination으로 이동시킬 대상입니다. / 인 경우 전체 파일을 지정하게 됩니다.
# destination -> 파일을 받을 위치입니다.
  - source: /
#    destination: /home/ec2-user/app/step2/zip/
    # 무중단 배포는 step3 사용
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

# permissions -> CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# hooks:
# -CodeDeploy 배포 단계에서 실행할 명령어를 지정
# -ApplicationStart 라는 단계에서 deploy.sh를 ec2-user 권한으로 실행
# -timeout:60으로 스크립트 실행 60초 이상 수행되면 실패 처리
hooks:
  # 무중단 배포 관련 추가
  AfterInstall:
    - location: stop.sh # Nginx와 연결되어 있지 않은 스프링 부트를 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
#    - location: deploy.sh
# 무중단 배포 관련 변경
    - location: start.sh # Nginx와 연결되어 있지 않은 Port로 새 버전의 스프링 부트를 시작
      timeout: 60
      runas: ec2-user
  # 무중단 배포 관련 추가
  ValidateService:
    - location: health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user
