# CodeDeploy 버전
# 프로젝트 버전이 아니므로 0.0 외에 다른 버전을 사용하면 오류 발생
version: 0.0
os: linux
files:
# source -> 전달해준 파일 중 destination으로 이동시킬 대상입니다. / 인 경우 전체 파일을 지정하게 됩니다.
# destination -> 파일을 받을 위치입니다.
  - source: /
    destination: /home/ec2-user/app/step2/zip/
    overwrite: yes

# permissions -> CodeDeploy에서 EC2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록
permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

# hooks:
# -CodeDeploy 배포 단계에서 실행할 명령어를 지정
# -ApplicationStart 라는 단계에서 deploy.sh를 ec2-user 권한으로 실행
# -timeout:60으로 스크립트 실행 60초 이상 수행되면 실패 처리
hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ec2-user